name: Deploy Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Frontend Container
        run: |
          cd ~/portfolio-app/portfolio-cli
          git fetch origin main
          git reset --hard origin/main
          cd ~/portfolio-app
          docker compose up -d --build frontend
